# Generated by Django 5.2.5 on 2025-09-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название аэропорта')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код (IATA/ICAO)')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название службы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Номер рейса')),
                ('departure_time', models.DateTimeField(verbose_name='Время вылета (план)')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прилета (план)')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время вылета')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время прилета')),
                ('violation_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид нарушения')),
                ('violation_details', models.TextField(blank=True, null=True, verbose_name='Детали нарушения')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport', verbose_name='Аэропорт прилета')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport', verbose_name='Аэропорт вылета')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.service', verbose_name='Ответственная служба')),
            ],
        ),
    ]
